tlsPrivateKeyFile: /var/lib/kubelet/pki/kubelet.key
tlsCertFile: /var/lib/kubelet/pki/kubelet.crt
protectKernelDefaults: true
tlsCipherSuites:
- TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
- TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256